export const CellTypes = [
  { label: "Text", value: "TEXT" },
  { label: "Text Area", value: "TEXT_AREA" },
  { label: "Phone Number", value: "PHONENUMBER" },
  { label: "Email", value: "EMAIL" },
  { label: "Number", value: "NUMBER" },
  { label: "Decimal", value: "DECIMAL" },
  { label: "Rate", value: "RATE" },
  { label: "Dropdown", value: "DROPDOWN" },
  { label: "Image", value: "IMAGE" },
  { label: "DateTime", value: "DATETIME" },
  { label: "Currency", value: "CURRENCY" },
  { label: "Checkbox", value: "CHECKBOX" },
  { label: "Radio", value: "RADIO" },
  { label: "Officer Select", value: "OFFICER_SELECT" },
  { label: "Scan Qr", value: "SCAN_QR" },
  { label: "Document", value: "LOUNGE_FILE" },
  { label: "Contact", value: "CONTACT" },
  { label: "Map", value: "MAP" },
  { label: "ITEM_LIST", value: "ITEM_LIST" },
  { label: "Nested Dropdown", value: "NESTED_DROPDOWN" },
  { label: "Audit", value: "AUDIT" },
];
export const DummyInitValues = {
  TEXT: "",
  TEXT_AREA: "",
  PHONENUMBER: "",
  EMAIL: "",
  NUMBER: "",
  DECIMAL: "",
  RATE: 0,
  IMAGE: "",
  DATETIME: "",
  DROPDOWN: "",
  READONLY_TEXT: "",
  SWITCH: false,
  CURRENCY: "",
  CHECKBOX: [],
  RADIO: "",
  OFFICER_SELECT: "",
  SCAN_QR: "",
  LOUNGE_FILE: "",
  CONTACT: "",
  MAP: "",
  ITEM_LIST: "",
  NESTED_DROPDOWN: {},
};
export const DocCells = ["IMAGE"];
