export const START_FETCHING_TABLE_DATA =
  "DYNAMIC_TABLE_START_FETCHING_TABLE_DATA";
export const FETCHING_TABLE_DATA_SUCCESS =
  "DYNAMIC_TABLE_FETCHING_TABLE_DATA_SUCCESS";
export const FETCHING_TABLE_DATA_FAILED =
  "DYNAMIC_TABLE_FETCHING_TABLE_DATA_FAILED";
export const CLEAR_TABLE_DATA = "DYNAMIC_TABLE_CLEAR_TABLE_DATA";

export const START_FETCHING_TABLE_HEADER =
  "DYNAMIC_TABLE_START_FETCHING_TABLE_HEADER";
export const FETCHING_TABLE_HEADER_SUCCESS =
  "DYNAMIC_TABLE_FETCHING_TABLE_HEADER_SUCCESS";
export const FETCHING_TABLE_HEADER_FAILED =
  "DYNAMIC_TABLE_FETCHING_TABLE_HEADER_FAILED";

export const START_UPDATING_FIELD = "DYNAMIC_TABLE_START_UPDATING_FIELD";
export const UPDATING_FIELD_DATA_SUCCESS =
  "DYNAMIC_TABLE_UPDATING_FIELD_DATA_SUCCESS";
export const UPDATING_CURRENT_REPORT_ID =
  "DYNAMIC_TABLE_UPDATING_CURRENT_REPORT_ID";
export const UPDATING_FIELD_DATA_FAILED =
  "DYNAMIC_TABLE_UPDATING_FIELD_DATA_FAILED";
export const UPDATE_FILTER_DATA = "DYNAMIC_TABLE_UPDATE_FILTER_DATA";
export const UPDATE_API_URL = "DYNAMIC_TABLE_UPDATE_API_URL";
export const UPDATE_REPORT_TYPE = "DYNAMIC_TABLE_UPDATE_REPORT_TYPE";
export const SET_ERROR = "DYNAMIC_TABLE_SET_ERROR";
export const REMOVE_ERROR = "DYNAMIC_TABLE_REMOVE_ERROR";
export const ADD_FREEZED_COLUMN = "DYNAMIC_TABLE_ADD_FREEZED_COLUMN";
export const REMOVE_FREEZED_COLUMN = "DYNAMIC_TABLE_REMOVE_FREEZED_COLUMN";
export const UPDATE_SNACKABR_STATUS = "DYNAMIC_TABLE_UPDATE_SNACKABR_STATUS";
export const START_UPLOAD_FILE = "DYNAMIC_TABLE_START_UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "DYNAMIC_TABLE_UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "DYNAMIC_TABLE_UPLOAD_FILE_FAILED";

export const START_ADD_CONTENT = "DYNAMIC_TABLE_START_ADD_CONTENT";
export const ADD_CONTENT_SUCCESS = "DYNAMIC_TABLE_ADD_CONTENT_SUCCESS";
export const ADD_CONTENT_FAILED = "DYNAMIC_TABLE_ADD_CONTENT_FAILED";

export const START_EDIT_CONTENT = "DYNAMIC_TABLE_START_EDIT_CONTENT";
export const EDIT_CONTENT_SUCCESS = "DYNAMIC_TABLE_EDIT_CONTENT_SUCCESS";
export const EDIT_CONTENT_FAILED = "DYNAMIC_TABLE_EDIT_CONTENT_FAILED";

export const START_DELETE_CONTENT = "DYNAMIC_TABLE_START_DELETE_CONTENT";
export const DELETE_CONTENT_SUCCESS = "DYNAMIC_TABLE_DELETE_CONTENT_SUCCESS";
export const DELETE_CONTENT_FAILED = "DYNAMIC_TABLE_DELETE_CONTENT_FAILED";

export const START_ADD_FIELD = "DYNAMIC_TABLE_START_ADD_FIELD";
export const ADD_FIELD_SUCCESS = "DYNAMIC_TABLE_ADD_FIELD_SUCCESS";
export const ADD_FIELD_FAILED = "DYNAMIC_TABLE_ADD_FIELD_FAILED";

export const START_EDIT_FIELD = "DYNAMIC_TABLE_START_EDIT_FIELD";
export const EDIT_FIELD_SUCCESS = "DYNAMIC_TABLE_EDIT_FIELD_SUCCESS";
export const EDIT_FIELD_FAILED = "DYNAMIC_TABLE_EDIT_FIELD_FAILED";

export const START_DELETE_FIELD = "DYNAMIC_TABLE_START_DELETE_FIELD";
export const DELETE_FIELD_SUCCESS = "DYNAMIC_TABLE_DELETE_FIELD_SUCCESS";
export const DELETE_FIELD_FAILED = "DYNAMIC_TABLE_DELETE_FIELD_FAILED";

export const UPDATING_QUERY_PARAMS = "DYNAMIC_TABLE_UPDATING_QUERY_PARAMS";
export const UPDATE_BEARER_TOKEN = "DYNAMIC_TABLE_UPDATE_BEARER_TOKEN";
export const FETCH_NEW_DATA = "DYNAMIC_TABLE_FETCH_NEW_DATA";
