export const START_FETCHING_TABLE_DATA = "START_FETCHING_TABLE_DATA";
export const FETCHING_TABLE_DATA_SUCCESS = "FETCHING_TABLE_DATA_SUCCESS";
export const FETCHING_TABLE_DATA_FAILED = "FETCHING_TABLE_DATA_FAILED";
export const CLEAR_TABLE_DATA = "CLEAR_TABLE_DATA";

export const START_FETCHING_TABLE_HEADER = "START_FETCHING_TABLE_HEADER";
export const FETCHING_TABLE_HEADER_SUCCESS = "FETCHING_TABLE_HEADER_SUCCESS";
export const FETCHING_TABLE_HEADER_FAILED = "FETCHING_TABLE_HEADER_FAILED";

export const START_UPDATING_FIELD = "START_UPDATING_FIELD";
export const UPDATING_FIELD_DATA_SUCCESS = "UPDATING_FIELD_DATA_SUCCESS";
export const UPDATING_CURRENT_REPORT_ID = "UPDATING_CURRENT_REPORT_ID";
export const UPDATING_FIELD_DATA_FAILED = "UPDATING_FIELD_DATA_FAILED";
export const UPDATE_FILTER_DATA = "UPDATE_FILTER_DATA";
export const UPDATE_API_URL = "UPDATE_API_URL";
export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
