export const START_FETCHING_TABLE_DATA = "START_FETCHING_TABLE_DATA";
export const FETCHING_TABLE_DATA_SUCCESS = "FETCHING_TABLE_DATA_SUCCESS";
export const FETCHING_TABLE_DATA_FAILED = "FETCHING_TABLE_DATA_FAILED";
export const CLEAR_TABLE_DATA = "CLEAR_TABLE_DATA";

export const START_FETCHING_TABLE_HEADER = "START_FETCHING_TABLE_HEADER";
export const FETCHING_TABLE_HEADER_SUCCESS = "FETCHING_TABLE_HEADER_SUCCESS";
export const FETCHING_TABLE_HEADER_FAILED = "FETCHING_TABLE_HEADER_FAILED";

export const START_UPDATING_FIELD = "START_UPDATING_FIELD";
export const UPDATING_FIELD_DATA_SUCCESS = "UPDATING_FIELD_DATA_SUCCESS";
export const UPDATING_CURRENT_REPORT_ID = "UPDATING_CURRENT_REPORT_ID";
export const UPDATING_FIELD_DATA_FAILED = "UPDATING_FIELD_DATA_FAILED";
export const UPDATE_FILTER_DATA = "UPDATE_FILTER_DATA";
export const UPDATE_API_URL = "UPDATE_API_URL";
export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const ADD_FREEZED_COLUMN = "ADD_FREEZED_COLUMN";
export const REMOVE_FREEZED_COLUMN = "REMOVE_FREEZED_COLUMN";

export const START_UPLOAD_FILE = "START_UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";

export const START_ADD_CONTENT = "START_ADD_CONTENT";
export const ADD_CONTENT_SUCCESS = "ADD_CONTENT_SUCCESS";
export const ADD_CONTENT_FAILED = "ADD_CONTENT_FAILED";

export const START_EDIT_CONTENT = "START_EDIT_CONTENT";
export const EDIT_CONTENT_SUCCESS = "EDIT_CONTENT_SUCCESS";
export const EDIT_CONTENT_FAILED = "EDIT_CONTENT_FAILED";

export const START_DELETE_CONTENT = "START_DELETE_CONTENT";
export const DELETE_CONTENT_SUCCESS = "DELETE_CONTENT_SUCCESS";
export const DELETE_CONTENT_FAILED = "DELETE_CONTENT_FAILED";

export const START_ADD_FIELD = "START_ADD_FIELD";
export const ADD_FIELD_SUCCESS = "ADD_FIELD_SUCCESS";
export const ADD_FIELD_FAILED = "ADD_FIELD_FAILED";

export const START_EDIT_FIELD = "START_EDIT_FIELD";
export const EDIT_FIELD_SUCCESS = "EDIT_FIELD_SUCCESS";
export const EDIT_FIELD_FAILED = "EDIT_FIELD_FAILED";

export const START_DELETE_FIELD = "START_DELETE_FIELD";
export const DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS";
export const DELETE_FIELD_FAILED = "DELETE_FIELD_FAILED";

export const UPDATING_QUERY_PARAMS = "UPDATING_QUERY_PARAMS";
export const FETCH_NEW_DATA = "FETCH_NEW_DATA";
